#Monitor authentication
-w /etc/passwd -p wa -k identity
-w /etc/shadow -p wa -k identity
-w /etc/sudoers -p wa -k sudoers

#Monitor login/logout

-w /var/log/faillog -p wa -k logins
-w /var/log/lastlog -p wa -k logins

#monitor SSH
-w /etc/ssh/sshd_config -p wa -k sshd

#monitor all commands run as root 

-a always,exit -F arch=b64 -F euid=0 -S execve -k root_commands

#monitor network connections
-a always,exit -F arch=b64 -S connect -k network_connect 
